const ROLES = Object.freeze({
  SUPER_ADMIN: 'SUPER_ADMIN',
  COMPANY_ADMIN: 'COMPANY_ADMIN',
  AGENT: 'AGENT',
  BROKER: 'BROKER',
  DEVELOPER: 'DEVELOPER',
  PROPERTY_MANAGER: 'PROPERTY_MANAGER',
  CUSTOMER: 'CUSTOMER',
});

// Roles that belong to a company workspace (i.e. are tenant-scoped staff).
// CUSTOMER is technically tenant-scoped too (tied to the company they're engaging with)
// but is handled slightly differently in queries (see tenant middleware).
const STAFF_ROLES = [
  ROLES.COMPANY_ADMIN,
  ROLES.AGENT,
  ROLES.BROKER,
  ROLES.DEVELOPER,
  ROLES.PROPERTY_MANAGER,
];

const LEAD_STATUS = Object.freeze({
  NEW: 'NEW',
  CONTACTED: 'CONTACTED',
  QUALIFIED: 'QUALIFIED',
  VISIT: 'VISIT',
  NEGOTIATION: 'NEGOTIATION',
  CLOSED: 'CLOSED',
  LOST: 'LOST',
});

const LEAD_STATUS_ORDER = [
  LEAD_STATUS.NEW,
  LEAD_STATUS.CONTACTED,
  LEAD_STATUS.QUALIFIED,
  LEAD_STATUS.VISIT,
  LEAD_STATUS.NEGOTIATION,
  LEAD_STATUS.CLOSED,
  LEAD_STATUS.LOST,
];

const PROPERTY_STATUS = Object.freeze({
  DRAFT: 'DRAFT',
  PUBLISHED: 'PUBLISHED',
  UNPUBLISHED: 'UNPUBLISHED',
  SOLD: 'SOLD',
  RENTED: 'RENTED',
});

const PROPERTY_TYPE = Object.freeze({
  APARTMENT: 'APARTMENT',
  VILLA: 'VILLA',
  PLOT: 'PLOT',
  INDEPENDENT_HOUSE: 'INDEPENDENT_HOUSE',
  PENTHOUSE: 'PENTHOUSE',
  STUDIO: 'STUDIO',
  COMMERCIAL_OFFICE: 'COMMERCIAL_OFFICE',
  COMMERCIAL_SHOP: 'COMMERCIAL_SHOP',
  FARMHOUSE: 'FARMHOUSE',
  WAREHOUSE: 'WAREHOUSE',
});

const LISTING_TYPE = Object.freeze({
  SALE: 'SALE',
  RENT: 'RENT',
});

const FURNISHING = Object.freeze({
  UNFURNISHED: 'UNFURNISHED',
  SEMI_FURNISHED: 'SEMI_FURNISHED',
  FULLY_FURNISHED: 'FULLY_FURNISHED',
});

const UNIT_STATUS = Object.freeze({
  AVAILABLE: 'AVAILABLE',
  RESERVED: 'RESERVED',
  SOLD: 'SOLD',
  BLOCKED: 'BLOCKED',
});

const APPOINTMENT_STATUS = Object.freeze({
  REQUESTED: 'REQUESTED',
  CONFIRMED: 'CONFIRMED',
  COMPLETED: 'COMPLETED',
  CANCELLED: 'CANCELLED',
});

const DEAL_STAGE = Object.freeze({
  OPEN: 'OPEN',
  WON: 'WON',
  LOST: 'LOST',
});

const CONSTRUCTION_STATUS = Object.freeze({
  PRE_LAUNCH: 'PRE_LAUNCH',
  UNDER_CONSTRUCTION: 'UNDER_CONSTRUCTION',
  READY_TO_MOVE: 'READY_TO_MOVE',
  COMPLETED: 'COMPLETED',
});

const NOTIFICATION_TYPE = Object.freeze({
  NEW_LEAD: 'NEW_LEAD',
  NEW_ENQUIRY: 'NEW_ENQUIRY',
  APPOINTMENT_REQUESTED: 'APPOINTMENT_REQUESTED',
  APPOINTMENT_CONFIRMED: 'APPOINTMENT_CONFIRMED',
  NEW_MESSAGE: 'NEW_MESSAGE',
  PRICE_CHANGE: 'PRICE_CHANGE',
  PROPERTY_SOLD: 'PROPERTY_SOLD',
  FOLLOW_UP_REMINDER: 'FOLLOW_UP_REMINDER',
  NEW_ASSIGNMENT: 'NEW_ASSIGNMENT',
});

const DOCUMENT_TYPE = Object.freeze({
  PROPERTY_DOCUMENT: 'PROPERTY_DOCUMENT',
  OWNERSHIP_DOCUMENT: 'OWNERSHIP_DOCUMENT',
  CONTRACT: 'CONTRACT',
  AGREEMENT: 'AGREEMENT',
  FLOOR_PLAN: 'FLOOR_PLAN',
  IDENTITY_DOCUMENT: 'IDENTITY_DOCUMENT',
});

const LEAD_SOURCE = Object.freeze({
  WEBSITE: 'WEBSITE',
  REFERRAL: 'REFERRAL',
  WALK_IN: 'WALK_IN',
  PHONE: 'PHONE',
  SOCIAL_MEDIA: 'SOCIAL_MEDIA',
  PROPERTY_PORTAL: 'PROPERTY_PORTAL',
  ADVERTISEMENT: 'ADVERTISEMENT',
  OTHER: 'OTHER',
});

module.exports = {
  ROLES,
  STAFF_ROLES,
  LEAD_STATUS,
  LEAD_STATUS_ORDER,
  PROPERTY_STATUS,
  PROPERTY_TYPE,
  LISTING_TYPE,
  FURNISHING,
  UNIT_STATUS,
  APPOINTMENT_STATUS,
  DEAL_STAGE,
  CONSTRUCTION_STATUS,
  NOTIFICATION_TYPE,
  DOCUMENT_TYPE,
  LEAD_SOURCE,
};
